using System.Collections.Generic;
using System.Threading.Tasks;
using BaseLib.Abstracts;
using BaseLib.Utils;
using Godot;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.CardPools;
using MegaCrit.Sts2.Core.Rooms;
using MegaCrit.Sts2.Core.Saves.Runs;
using ZoneTheSpire.Core.Scrapyard;
using ZoneTheSpire.Rendering;

namespace ZoneTheSpire.Run.Scrapyard;

/// <summary>
/// Curse from The Buried Automaton event. Innate and Unplayable; whenever it is drawn (the opening hand included: energy is
/// reset before the hand is drawn) its owner loses 2 energy. After 3 combats in the deck it transforms into Automaton Form.
/// Counts combats like vanilla Guilty (a saved property on the deck card, advanced in AfterCombatEnd on every peer). Never
/// generated at random: vanilla random curses skip cards that can't be generated by modifiers.
/// </summary>
[Pool(typeof(CurseCardPool))]
public sealed class ScrapyardAutomaton : CustomCardModel
{
    private const string CombatsKey = "Combats";
    private const string PortraitFile = "scrapyard_automaton.png";

    private int _combatsSeen;

    public ScrapyardAutomaton()
        : base(-1, CardType.Curse, CardRarity.Curse, TargetType.None)
    {
    }

    public override int MaxUpgradeLevel => 0;

    public override bool CanBeGeneratedByModifiers => false;

    public override bool CanBeGeneratedInCombat => false;

    public override IEnumerable<CardKeyword> CanonicalKeywords => new[] { CardKeyword.Innate, CardKeyword.Unplayable };

    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new EnergyVar(ScrapyardRules.AutomatonEnergyLoss),
        new DynamicVar(CombatsKey, ScrapyardRules.AutomatonCombats),
    };

    protected override IEnumerable<IHoverTip> ExtraHoverTips => new[] { HoverTipFactory.FromCard<AutomatonForm>() };

    public override Texture2D? CustomPortrait => ModTextures.GetCustom(PortraitFile);

    /// <summary>Combats this card has spent in its owner's deck. Saved with the run.</summary>
    [SavedProperty]
    public int CombatsSeen
    {
        get => _combatsSeen;
        set
        {
            AssertMutable();
            _combatsSeen = value;
            DynamicVars[CombatsKey].BaseValue = ScrapyardRules.AutomatonCombatsLeft(value);
        }
    }

    public override async Task AfterCardDrawn(PlayerChoiceContext choiceContext, CardModel card, bool fromHandDraw)
    {
        if (card != this)
        {
            return;
        }

        await Cmd.Wait(0.25f);
        await PlayerCmd.LoseEnergy(DynamicVars.Energy.IntValue, Owner);
    }

    public override async Task AfterCombatEnd(CombatRoom room)
    {
        if (Pile is not { Type: PileType.Deck })
        {
            return;
        }

        CombatsSeen++;
        if (ScrapyardRules.AutomatonAwakens(CombatsSeen))
        {
            await CardCmd.TransformTo<AutomatonForm>(this);
        }
    }
}
