using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.RestSite;
using MegaCrit.Sts2.Core.Hooks;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Map;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.CardPools;
using MegaCrit.Sts2.Core.Rewards;
using MegaCrit.Sts2.Core.Runs;
using ZoneTheSpire.Core.Mirror;
using ZoneTheSpire.Core.Shadow;

namespace ZoneTheSpire.Run.Campfire;

/// <summary>
/// Shadow Corruption Troubled Dreams (replaces Rest): heal like a normal Rest, then a 50% chance to add a random curse to the
/// deck. The roll and the curse are picked from the run seed, location and player (so every peer gets the same result), among
/// the curses the game hands out at random (those that can be generated by modifiers). The vanilla after-rest hooks and rest
/// rewards still run, like a normal rest. It is a free action: afterwards only this option is removed, and the player can still
/// take another campfire action (ZoneTheSpireModifier.ShouldDisableRemainingRestSiteOptions). Runs on every peer.
/// </summary>
public sealed class TroubledDreamsRestSiteOption : RestSiteOption
{
    /// <summary>
    /// Players whose last campfire choice was Troubled Dreams, until the rest site asks whether to lock the others. Each mark
    /// remembers its run and campfire, so a mark that was never consumed can't free an action anywhere else; RunLifecycle
    /// also clears them between runs.
    /// </summary>
    private static readonly Dictionary<ulong, (IRunState Run, string Location)> FreeActionPending = new();

    /// <summary>Whether the player just chose Troubled Dreams (a free action) at this campfire; consumes the mark.</summary>
    internal static bool ConsumeFreeAction(Player player) =>
        FreeActionPending.Remove(player.NetId, out var mark)
        && ReferenceEquals(mark.Run, player.RunState)
        && mark.Location == LocationOf(player);

    internal static void Reset() => FreeActionPending.Clear();

    private static string LocationOf(Player player)
    {
        MapCoord? coord = player.RunState.CurrentMapCoord;
        return MirrorDuplicateRules.LocationKey(player.RunState.CurrentActIndex, coord?.row, coord?.col, 0);
    }

    private readonly HealRestSiteOption _vanilla;

    public TroubledDreamsRestSiteOption(Player owner)
        : base(owner)
    {
        _vanilla = new HealRestSiteOption(owner);
        RestSiteLoc.EnsureInjected();
    }

    public override string OptionId => RestSiteLoc.TroubledDreamsId;

    public override IEnumerable<string> AssetPaths => _vanilla.AssetPaths;

    /// <summary>Same variables as HealRestSiteOption.Description (the normal Rest heal and its preview).</summary>
    public override LocString Description
    {
        get
        {
            LocString description = base.Description;
            var heal = new HealVar(HealRestSiteOption.GetBaseHealAmount(Owner.Creature))
            {
                PreviewValue = HealRestSiteOption.GetHealAmount(Owner),
            };
            description.Add("Character", Owner.Character.Id.Entry);
            description.Add(heal);
            IReadOnlyList<LocString> extra = Hook.ModifyExtraRestSiteHealText(Owner.RunState, Owner, Array.Empty<LocString>());
            description.Add("ExtraText", extra.Any() ? "\n" + string.Join("\n", extra.Select(text => text.GetFormattedText())) : string.Empty);
            return description;
        }
    }

    public override async Task<bool> OnSelect()
    {
        decimal amount = HealRestSiteOption.GetHealAmount(Owner);
        await CreatureCmd.Heal(Owner.Creature, amount);

        string location = LocationOf(Owner);
        CardModel? curse = null;
        if (ShadowRules.TroubledDreamsCurses(Owner.RunState.Rng.Seed, location, Owner.NetId))
        {
            List<CardModel> curses = ModelDb.CardPool<CurseCardPool>()
                .GetUnlockedCards(Owner.UnlockState, Owner.RunState.CardMultiplayerConstraint)
                .Where(card => card.CanBeGeneratedByModifiers)
                .OrderBy(card => card.Id.Entry, StringComparer.Ordinal)
                .ToList();
            int index = ShadowRules.PickCurseIndex(Owner.RunState.Rng.Seed, location, Owner.NetId, curses.Count);
            if (index >= 0)
            {
                curse = curses[index];
                await CardPileCmd.AddCursesToDeck(new[] { curse }, Owner);
            }
        }

        // The rest of HealRestSiteOption.ExecuteRestSiteHeal: after-rest hooks and rest rewards.
        await Hook.AfterRestSiteHeal(Owner.RunState, Owner, isMimicked: false);
        var rewards = new List<Reward>();
        Hook.ModifyRestSiteHealRewards(Owner.RunState, Owner, rewards, isMimicked: false);
        await RewardsCmd.OfferCustom(Owner, rewards);

        // Right after this returns, the rest site asks whether to lock the other options; this mark says no (once).
        FreeActionPending[Owner.NetId] = (Owner.RunState, LocationOf(Owner));
        return true;
    }

    public override Task DoLocalPostSelectVfx(CancellationToken ct = default) => _vanilla.DoLocalPostSelectVfx(ct);

    public override Task DoRemotePostSelectVfx() => _vanilla.DoRemotePostSelectVfx();
}
